# Generated by Django 4.2.4 on 2023-09-03 13:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="projectidea",
            name="code",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name="projectshowcase",
            name="code",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
