# Generated by Django 4.2.4 on 2023-09-03 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("projects", "0002_projectidea_code_projectshowcase_code"),
    ]

    operations = [
        migrations.RenameField(
            model_name="url",
            old_name="title",
            new_name="website",
        ),
        migrations.AlterField(
            model_name="url",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="url",
                to="projects.projectshowcase",
            ),
        ),
    ]
